### ISSUE TITLE
Práctica 7_Pruebas Unitarias En El Contrato Inteligente.

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-11-practica-de-pruebas-unitarias-equipo-ycee#1]
[Práctica 7_Pruebas Unitarias En El Contrato Inteligente..pdf](https://github.com/user-attachments/files/15507562/Practica.7_Pruebas.Unitarias.En.El.Contrato.Inteligente.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
